# Generated by Django 5.2.8 on 2025-11-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_explanation_task_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='score',
        ),
    ]
