# Generated by Django 5.2.8 on 2025-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_explanation_remove_task_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='strategy',
            field=models.CharField(default='smart_balance', max_length=50),
        ),
    ]
